export const occasions = {
  birthday: {
    id: 'birthday',
    name: 'Birthday',
    defaultFilter: 'softGlow',
    backgroundColors: ['#FFD700', '#FF69B4', '#87CEEB', '#F5F5F5', '#FFF8DC'],
    stickers: [
      
      { name: 'Garlands', url: '/stickers/birthday/002-garlands.png' },
      { name: 'Cake', url: '/stickers/birthday/003-cake.png' },
      { name: 'Birthday Hat', url: '/stickers/birthday/004-birthday-hat.png' },
      { name: 'Party Cake', url: '/stickers/birthday/005-birthday-cake.png' },
      { name: 'Balloons', url: '/stickers/birthday/006-balloons.png' },
      { name: 'Gift', url: '/stickers/birthday/007-gift.png' },
      { name: 'Cake 2', url: '/stickers/birthday/008-birthday-cake-1.png' },
      { name: 'Balloons 2', url: '/stickers/birthday/009-balloons-1.png' },
      { name: 'Confetti 2', url: '/stickers/birthday/010-confetti-1.png' },
      { name: 'Garland', url: '/stickers/birthday/011-garland.png' },
      { name: 'Balloons 3', url: '/stickers/birthday/012-balloons-2.png' },
      { name: 'Gifts', url: '/stickers/birthday/013-gifts.png' },
      { name: 'Card', url: '/stickers/birthday/014-birthday-card.png' },
      { name: 'Balloons New', url: '/stickers/birthday/balloons.png' },
      { name: 'Birthday 3', url: '/stickers/birthday/birthday-3.png' },
      { name: 'Birthday 4', url: '/stickers/birthday/birthday-4.png' },
      { name: 'Birthday 5', url: '/stickers/birthday/birthday-5.png' },
      { name: 'Birthday 6', url: '/stickers/birthday/birthday-6.png' },
      { name: 'Birthday Cake 2', url: '/stickers/birthday/birthday-cake-2.png' },
      { name: 'Birthday Cake 3', url: '/stickers/birthday/birthday-cake-3.png' },
      { name: 'Birthday Cake 4', url: '/stickers/birthday/birthday-cake-4.png' },
      { name: 'Birthday Cake 5', url: '/stickers/birthday/birthday-cake-5.png' },
      { name: 'Birthday', url: '/stickers/birthday/birthday.png' },
      { name: 'Cupcake 2', url: '/stickers/birthday/cupcake-2.png' },
      { name: 'Cupcake 3', url: '/stickers/birthday/cupcake-3.png' },
      { name: 'Cupcake', url: '/stickers/birthday/cupcake.png' },
      { name: 'Gift 2', url: '/stickers/birthday/gift-2.png' },
      { name: 'Gift 3', url: '/stickers/birthday/gift-3.png' },
      { name: 'Gift Default', url: '/stickers/birthday/gift.png' },
      { name: 'Ice Cream', url: '/stickers/birthday/ice-cream.png' },
    ],
  },
  wedding: {
    id: 'wedding',
    name: 'Wedding',
    defaultFilter: 'normal',
    backgroundColors: ['#aa5097ff', '#e1c966ff', '#ea667aff', '#9a9ae6ff', '#56738dff'],
    stickers: [
      { name: 'Wedding 2', url: '/stickers/wedding/001-wedding-2.png' },
      { name: 'Wedding (old)', url: '/stickers/wedding/001-wedding.png' },
      { name: 'Marriage', url: '/stickers/wedding/002-marriage.png' },
      { name: 'Wedding Couple (old)', url: '/stickers/wedding/002-wedding-couple.png' },
      { name: 'Couple', url: '/stickers/wedding/003-couple.png' },
      { name: 'Just Married (old)', url: '/stickers/wedding/004-just-married.png' },
      { name: 'Marriage 1', url: '/stickers/wedding/005-marriage.png' },
      { name: 'Heart Cake', url: '/stickers/wedding/006-heart-cake.png' },
      { name: 'Dance', url: '/stickers/wedding/007-dance.png' },
      { name: 'Balloons 2', url: '/stickers/wedding/balloons-2.png' },
      { name: 'Bouquet 2', url: '/stickers/wedding/bouquet-2.png' },
      { name: 'Bouquet', url: '/stickers/wedding/bouquet.png' },
      { name: 'Bridesmaids', url: '/stickers/wedding/bridesmaids.png' },
      { name: 'Drinking', url: '/stickers/wedding/drinking.png' },
      { name: 'Just Married', url: '/stickers/wedding/just-married.png' },
      { name: 'Love Message', url: '/stickers/wedding/love-message.png' },
      { name: 'Love You', url: '/stickers/wedding/love-you.png' },
      { name: 'Love', url: '/stickers/wedding/love.png' },
      { name: 'Toast', url: '/stickers/wedding/toast.png' },
      { name: 'Wedding 2 New', url: '/stickers/wedding/wedding-2.png' },
      { name: 'Wedding 3', url: '/stickers/wedding/wedding-3.png' },
      { name: 'Wedding Arch', url: '/stickers/wedding/wedding-arch.png' },
      { name: 'Wedding Couple 2', url: '/stickers/wedding/wedding-couple-2.png' },
      { name: 'Wedding Couple 3', url: '/stickers/wedding/wedding-couple-3.png' },
      { name: 'Wedding Couple 4', url: '/stickers/wedding/wedding-couple-4.png' },
      { name: 'Wedding Couple', url: '/stickers/wedding/wedding-couple.png' },
      { name: 'Wedding Day', url: '/stickers/wedding/wedding-day.png' },
      { name: 'Wedding Invitation', url: '/stickers/wedding/wedding-invitation.png' },
      { name: 'Wedding Rings', url: '/stickers/wedding/wedding-rings.png' },
      { name: 'Wedding', url: '/stickers/wedding/wedding.png' },
    ],
  },
  graduation: {
    id: 'graduation',
    name: 'Graduation',
    defaultFilter: 'normal',
    backgroundColors: ['#003366', '#000000', '#FFD700', '#FFFFFF', '#C0C0C0'],
    stickers: [
      { name: 'Graduate', url: '/stickers/graduation/001-graduate.png' },
      { name: 'Education', url: '/stickers/graduation/002-education.png' },
      { name: 'Congratulation', url: '/stickers/graduation/003-congratulation.png' },
      { name: 'Graduate 1', url: '/stickers/graduation/004-graduate-1.png' },
      { name: 'Graduated', url: '/stickers/graduation/005-graduated.png' },
      { name: 'Graduate 2', url: '/stickers/graduation/006-graduate-2.png' },
      { name: 'Scroll', url: '/stickers/graduation/007-scroll.png' },
      { name: 'Hat', url: '/stickers/graduation/008-graduate-hat.png' },
      { name: 'Graduate 3', url: '/stickers/graduation/009-graduate-3.png' },
      { name: 'Scroll 1', url: '/stickers/graduation/010-scroll-1.png' },
      { name: 'Student', url: '/stickers/graduation/011-student.png' },
      { name: 'Magistrate', url: '/stickers/graduation/012-magistrate.png' },
      { name: 'Graduation', url: '/stickers/graduation/013-graduation.png' },
      { name: 'Group', url: '/stickers/graduation/014-group.png' },
      { name: 'Education 1', url: '/stickers/graduation/015-education-1.png' },
    ],
  },
  datenight: {
    id: 'datenight',
    name: 'Date Night',
    defaultFilter: 'softGlow',
    backgroundColors: ['#FF1493', '#FFB6C1', '#FFF0F5', '#E6E6FA', '#F5F5F5'],
    stickers: [
      { name: 'Date Night', url: '/stickers/date night/001-date-night.png' },
      { name: 'Calendar', url: '/stickers/date night/002-calendar.png' },
      { name: 'Romantic Date', url: '/stickers/date night/003-romantic-date.png' },
      { name: 'Date', url: '/stickers/date night/004-date.png' },
      { name: 'Day Night', url: '/stickers/date night/005-day-and-night.png' },
      { name: 'Date 1', url: '/stickers/date night/006-date-1.png' },
      { name: 'Heart', url: '/stickers/date night/007-heart.png' },
      { name: 'In Love', url: '/stickers/date night/008-in-love.png' },
      { name: 'Hearts', url: '/stickers/date night/009-hearts.png' },
      { name: 'Love', url: '/stickers/date night/010-love.png' },
      { name: 'Hand', url: '/stickers/date night/011-hand.png' },
      { name: 'Love Letter', url: '/stickers/date night/012-love-letter.png' },
      { name: 'Balloons', url: '/stickers/date night/013-balloons.png' },
      { name: 'Kiss', url: '/stickers/date night/014-kiss.png' },
      { name: 'Heart 1', url: '/stickers/date night/015-heart-1.png' },
      { name: 'Smile', url: '/stickers/date night/016-smile.png' },
      { name: 'Heart 2', url: '/stickers/date night/017-heart-2.png' },
      { name: 'Love 1', url: '/stickers/date night/018-love-1.png' },
      { name: 'Love Letter 1', url: '/stickers/date night/019-love-letter-1.png' },
      { name: 'In Love 1', url: '/stickers/date night/020-in-love-1.png' },
    ],
  },
  casual: {
    id: 'casual',
    name: 'Casual',
    defaultFilter: 'normal',
    backgroundColors: ['#FF9AA2', '#FFB7B2', '#FFDAC1', '#E2F0CB', '#B5EAD7'],
    stickers: [
      { name: 'High Five', url: '/stickers/casual/001-high-five.png' },
      { name: 'Friendship', url: '/stickers/casual/002-friendship.png' },
      { name: 'Friends', url: '/stickers/casual/003-friends.png' },
      { name: 'Good Vibes', url: '/stickers/casual/004-good-vibes.png' },
      { name: 'Friends 1', url: '/stickers/casual/005-friends-1.png' },
      { name: 'Friend', url: '/stickers/casual/006-friend.png' },
    ],
  },
  natural: {
    id: 'natural',
    name: 'Natural',
    defaultFilter: 'softGlow',
    backgroundColors: ['#b96190', '#6d2732', '#5cb0d5', '#e4cf7d', '#5dd2a3'],
    stickers: [
      { name: 'Flower 2', url: '/stickers/natural/001-flower-2.png' },
      { name: 'Sakura', url: '/stickers/natural/002-sakura.png' },
      { name: 'Tulips', url: '/stickers/natural/003-tulips.png' },
      { name: 'Flower', url: '/stickers/natural/004-flower.png' },
      { name: 'Cherry Blossom', url: '/stickers/natural/005-cherry-blossom.png' },
      { name: 'Bouquet', url: '/stickers/natural/006-bouquet.png' },
      { name: 'Flower 1', url: '/stickers/natural/007-flower-1.png' },
      { name: 'Flower 3', url: '/stickers/natural/008-flower-3.png' },
      { name: 'Iris', url: '/stickers/natural/009-iris.png' },
      { name: 'Flowers', url: '/stickers/natural/010-flowers.png' },
      { name: 'Flower Bouquet', url: '/stickers/natural/011-flower-bouquet.png' },
      { name: 'Hibiscus', url: '/stickers/natural/012-hibiscus.png' },
      { name: 'Sakura 1', url: '/stickers/natural/013-sakura-1.png' },
      { name: 'Pink Cosmos', url: '/stickers/natural/014-pink-cosmos.png' },
      { name: 'Hibiscus 1', url: '/stickers/natural/015-hibiscus-1.png' },
      { name: 'Flower 4', url: '/stickers/natural/016-flower-4.png' },
      { name: 'Lavender', url: '/stickers/natural/017-lavender.png' },
      { name: 'Bouquet 1', url: '/stickers/natural/018-bouquet-1.png' },
      { name: 'Cute', url: '/stickers/natural/019-cute.png' },
      { name: 'Flowers 1', url: '/stickers/natural/020-flowers-1.png' },
      { name: 'Flowers 2', url: '/stickers/natural/021-flowers-2.png' },
      { name: 'Rose', url: '/stickers/natural/022-rose.png' },
      { name: 'Tulip', url: '/stickers/natural/023-tulip.png' },
      { name: 'Flower 5', url: '/stickers/natural/024-flower-5.png' },
      { name: 'Flower 6', url: '/stickers/natural/025-flower-6.png' },
      { name: 'Flower Bouquet 1', url: '/stickers/natural/026-flower-bouquet-1.png' },
      { name: 'Sakura 2', url: '/stickers/natural/027-sakura-2.png' },
      { name: 'Mexican Aster', url: '/stickers/natural/028-mexican-aster.png' },
      { name: 'Daisy', url: '/stickers/natural/029-daisy.png' },
      { name: 'Anemone', url: '/stickers/natural/030-anemone.png' },
      
    ],
  },
};